services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mattis
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: freizeitpark
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - freizeitpark_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/freizeitpark
      SPRING_DATASOURCE_USERNAME: mattis
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - freizeitpark_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - freizeitpark_network

volumes:
  pgdata:

networks:
  freizeitpark_network:
    driver: bridge
